manifest:
  version: "0.12"

  defaults:
    remote: zmkfirmware

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

projects:
  - name: zephyr
    repo-path: zephyr
    # ✅ 改这里，改成 zmkfirmware/zmk-zephyr 分支
    revision: zmk-zephyr
    import:
      path-prefix: zephyr
      file: west.yml


    - name: zmk
      repo-path: zmk
      revision: main
      import: app/west.yml

  self:
    path: app
