manifest:
  version: "0.12"

  defaults:
    remote: zmkfirmware

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zephyr
      repo-path: zephyr
      revision: v3.5.0
      import:
        path-prefix: zephyr
        file: west.yml

    - name: zmk
      repo-path: zmk
      revision: main
      import: app/west.yml

  self:
    path: app
