jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y ninja-build gperf ccache dfu-util device-tree-compiler wget \
              python3-pip python3-setuptools python3-wheel xz-utils file make gcc g++ cmake git

      - name: Export environment variables for Zephyr SDK
        run: |
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV

      - name: Init West
        run: |
          pip install west
          west init -l --mf west.yml
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          cd config
          west build -s ../zmk/app -d build -b nice_nano_v2 -- -DZMK_CONFIG=`pwd`
