      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Zephyr environment
        uses: zephyrproject-rtos/action-zephyr-setup@v1

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            ninja-build gperf ccache dfu-util device-tree-compiler wget \
            python3-pip python3-setuptools python3-wheel xz-utils file make gcc g++ cmake git

      - name: Download Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          mv zephyr-sdk-0.16.4 $HOME/zephyr-sdk

      - name: Set environment variables
        run: |
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV
