name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Zephyr environment
        uses: zephyrproject-rtos/action-zephyr-setup@v1

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            ninja-build gperf ccache dfu-util device-tree-compiler wget \
            python3-pip python3-setuptools python3-wheel xz-utils file make gcc g++ cmake git

      - name: Set environment variables
        run: |
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV

      - name: Install west and init project
        run: |
          pip install west
          west init -l --mf west.yml
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          cd config
          west build -s ../zmk/app -d build/nice_nano_v2 \
            -b nice_nano_v2 -- -DZMK_CONFIG=$(pwd)

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware-nice_nano_v2
          path: config/build/nice_nano_v2/zephyr/zmk.uf2
